services:
  hillir-init:
    image: aldovadev/hillir-test-api:latest
    container_name: hillir-init
    command: sh -c "npx prisma db push && npm run seed"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - hillir-db
    networks:
      - hillir_default
    restart: "on-failure"

  hillir-test-api:
    image: aldovadev/hillir-test-api:latest
    container_name: hillir-test-api
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - hillir_default
    depends_on:
      - hillir-init
    restart: unless-stopped

  hillir-db:
    container_name: hillir-db
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - hillir-data:/var/lib/postgresql/data
    networks:
      - hillir_default

networks:
  hillir_default:

volumes:
  hillir-data:
