services:
  my-express-api:
    image: myorg/my-express-api:production
    container_name: my-express-api
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "3000:3000"
    networks:
      - myapp_default
    depends_on:
      - my-postgres-db
    restart: unless-stopped

  my-postgres-db:
    container_name: my-postgres-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - myapp-db-data:/var/lib/postgresql/data
    networks:
      - myapp_default

networks:
  myapp_default:

volumes:
  myapp-db-data:
