openapi: 3.1.0
info:
  title: Hillir Test API
  version: 1.0.0
  description: API Documentation for Hillir Test Ad Performance Management
servers:
  - url: http://localhost:8000
    description: Local Dev Server

paths:
  /underperforming-ads:
    get:
      summary: Get Underperforming Ads
      description: Returns list of underperforming ads filtered by date, client, and KPI type.
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: Date of the ad performance (yyyy-mm-dd)
        - in: query
          name: client_id
          schema:
            type: integer
          description: Client ID to filter
        - in: query
          name: kpi_type_id
          schema:
            type: integer
          description: KPI Type ID to filter
      responses:
        '200':
          description: List of underperforming ads
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        client_name:
                          type: string
                        kpi_type:
                          type: string
                        kpi_target:
                          type: number
                        actual_value:
                          type: number
                        date:
                          type: string
                          format: date
        '500':
          description: Server error

  /ad-performances:
    post:
      summary: Add Ad Performance Data (Batch)
      description: Accepts batch ad performance data with submission information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                submitted_by:
                  type: string
                  example: "aldova"
                  description: The user or system submitting the data
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      client_id:
                        type: integer
                        example: 1
                      contract_id:
                        type: integer
                        example: 1
                      kpi_type_id:
                        type: integer
                        example: 1
                      actual_value:
                        type: number
                        example: 0.018
                      date:
                        type: string
                        format: date
                        example: "2025-06-01"
            example:
              submitted_by: "aldova"
              data:
                - client_id: 1
                  contract_id: 1
                  kpi_type_id: 1
                  actual_value: 0.018
                  date: "2025-06-01"
                - client_id: 1
                  contract_id: 2
                  kpi_type_id: 2
                  actual_value: 8700
                  date: "2025-06-01"
                - client_id: 2
                  contract_id: 3
                  kpi_type_id: 1
                  actual_value: 0.028
                  date: "2025-06-01"
                - client_id: 2
                  contract_id: 4
                  kpi_type_id: 2
                  actual_value: 7900
                  date: "2025-06-01"
                - client_id: 3
                  contract_id: 5
                  kpi_type_id: 1
                  actual_value: 0.027
                  date: "2025-06-01"
                - client_id: 3
                  contract_id: 6
                  kpi_type_id: 2
                  actual_value: 9400
                  date: "2025-06-01"
      responses:
        '201':
          description: Ad performances created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  created_count:
                    type: integer
        '400':
          description: Invalid request body
        '500':
          description: Server error

  /job-logs:
    get:
      summary: Get Job Logs
      description: Returns list of job logs filtered by status (optional).
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [success, failed]
          required: false
          description: Filter by job status
      responses:
        '200':
          description: List of job logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        job_type:
                          type: string
                        status:
                          type: string
                          enum: [success, failed]
                        started_at:
                          type: string
                          format: date-time
                        finished_at:
                          type: string
                          format: date-time
                        duration_ms:
                          type: integer
                        message:
                          type: string

  /submission-logs:
    get:
      summary: Get Submission Logs
      description: Returns list of performance submissions, optionally filtered by submitter name.
      parameters:
        - in: query
          name: submitted_by
          schema:
            type: string
          required: false
          description: Filter by submitter name
      responses:
        '200':
          description: List of submission logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        submitted_by:
                          type: string
                        submitted_at:
                          type: string
                          format: date-time
                        row_count:
                          type: integer
                        client_id:
                          type: integer
